/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://nbo3citw7nchpggquzv7pz7jvu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-y2vl5z5eorfalnphzjyhiwwefu",
    "aws_cognito_identity_pool_id": "us-west-2:b25a16f8-f42e-42f9-866e-c33f86bc05d6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_blHG61dZ0",
    "aws_user_pools_web_client_id": "4pivv0dmragk2etb02klphd54s",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
